name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  this-can-be-anything-flow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@PhilipRidderheim'
      
  use-output:
    runs-on: ubuntu-latest
    needs: [this-can-be-anything-flow]
    steps:
      - run: echo "The time was ${{ needs.this-can-be-anything-flow.outputs.current-time }} when the action said hello"
